export const SHOW_HOVER_PLACE_INFOBOX = "SHOW_HOVER_PLACE_INFOBOX";
export const SHOW_ACTIVE_PLACE_INFOBOX = "SHOW_ACTIVE_PLACE_INFOBOX";
export const CLOSE_INFOBOX = "CLOSE_INFOBOX";

export const ADD_PLACE = "ADD_PLACE";

export const GET_ALL_PLACES = "GET_ALL_PLACES";

export const GET_USER_PLACES = "GET_USER_PLACES";
