export const SHOW_INFOBOX = "SHOW_INFOBOX";
export const CLOSE_INFOBOX = "CLOSE_INFOBOX";

export const ADD_PLACE = "ADD_PLACE";
export const ADD_PLACE_SUCCESS = "ADD_PLACE_SUCCESS";
export const ADD_PLACE_FAILURE = "ADD_PLACE_FAILURE";

export const GET_USER_PLACES = "GET_USER_PLACES";
export const GET_USER_PLACES_SUCCESS = "GET_USER_PLACES_SUCCESS";
export const GET_USER_PLACES_FAILURE = "GET_USER_PLACES_FAILURE";

export const GET_ALL_PLACES = "GET_ALL_PLACES";
export const GET_ALL_PLACES_SUCCESS = "GET_ALL_PLACES_SUCCESS";
export const GET_ALL_PLACES_FAILURE = "GET_ALL_PLACES_FAILURE";
