// NOTE: registration and login is handled with local state
export const AUTHENTICATE_USER = "AUTHENTICATE_USERS";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USERS_SUCCESS";
export const AUTHENTICATE_USER_ERROR = "AUTHENTICATE_USERS_ERROR";
